# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
   adapter: mysql2
   encoding: utf8
   database: mysql
   host: localhost
   username: root
   password: qCwu?$9t4YXW
