# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: brandslip_test_db
  host: localhost
  port: 5432
  username: joe
  password: Elprup1!
  
test:
  adapter: postgresql
  encoding: unicode
  database: brandslip_test_db
  host: localhost
  port: 5432
  username: joe
  password: Elprup1!

production:
  adapter: postgresql
  encoding: unicode
  database: brandslip_test_db
  host: localhost
  port: 5432
  username: joe
  password: Elprup1!